kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: onlineer/minimalist-web-notepad
      tags:
        - latest
    when:
      branch:
        -master

trigger:
  event:
    - pull_request


---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: plugins/webhook
    settings:
      urls:
        from_secret: deploy_webhook

trigger:
  event:
    - promote
  target:
    - production
