kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: onlineer/minimalist-web-notepad
      tags:
        - latest

trigger:
  branch:
  - master


---
kind: pipeline
name: deploy

steps:
  - name: deploy
    image: plugins/webhook
    settings:
      urls:
        from_secret: deploy_webhook

trigger:
  event:
    - promote
  target:
    - production
