version: "2.4"
services:
  minimalist-web-notepad:
    build: .
    container_name: minimalist-web-notepad
    restart: always
    ports:
     - "4080:80"
    volumes:
     - data:/var/www/html/_tmp

volumes:
  data:
